export const marcas = [{"marca":"Nissan"},
{"marca":"BMW"},
{"marca":"Ford"},
{"marca":"Chrysler"},
{"marca":"Ford"},
{"marca":"Mercury"},
{"marca":"Mitsubishi"},
{"marca":"Audi"},
{"marca":"Cadillac"},
{"marca":"Toyota"},
{"marca":"Nissan"},
{"marca":"Jaguar"},
{"marca":"Nissan"},
{"marca":"Mitsubishi"},
{"marca":"Dodge"}];